name: Deploy website
on:
  pull_request:
    branches:
      - master
jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: npm-scan
        run: |
            npm audit
        
